name: Release project

on:
  push:
    # trigger by tags, like 'v0.0.1'
    tags:
      - "v*"

jobs:
  release:
    name: Release on Github
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        # see https://goreleaser.com/ci/actions/
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .github/goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
